# Generated by Django 4.2.3 on 2023-10-23 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user1app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='description',
            new_name='bio',
        ),
    ]
