# Generated by Django 4.2.3 on 2023-10-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user1app', '0003_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='post',
            field=models.FileField(null=True, upload_to='media'),
        ),
    ]
