# Generated by Django 4.2.3 on 2023-10-25 19:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user1app', '0004_alter_upload_post'),
        ('usersapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='follow',
            new_name='follow_model',
        ),
    ]
